# Generated by Django 4.1.4 on 2023-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.CharField(default='No info', max_length=100),
        ),
    ]
